nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome em maisculas é. {nome.upper()}')
print(f'Seu nome em minusculas é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")}')
#print(f'Seu primeiro nome é {nome.find(" ")} e ele tem ')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]}, e ele tem {len(separa[0])} letras')